const imgroute = "/static/images/theme/default/";
const defaults = {
    add: imgroute + "add.png",
    Customperiod: imgroute + "Customperiod.png",
    Recentmonth: imgroute + "Recentmonth.png",
    today: imgroute + "today.png",
    week: imgroute + "week.png",
    home: imgroute + "home.png",
    homechoose: imgroute + "homechoose.png",
    money: imgroute + "money.png",
    moneychoose: imgroute + "moneychoose.png",
    my: imgroute + "my.png",
    mychoose: imgroute + "mychoose.png",
    orderlist: imgroute + "orderlist.png",
    orderlistchoose: imgroute + "orderlistchoose.png",
    merge: imgroute + "merge.png",
    choose: imgroute + "choose.png",
    unchoose:imgroute + "unchoose.png",
    qmenu:imgroute + "qmenu.png",
    addimg:imgroute + "add-img.png",
    edit:imgroute + "edit.png",
    imagedelete:imgroute + "improve.png",
    general:imgroute + "general.png",
    shopmanage:imgroute + "shopmanage.png",
    update:imgroute + "update.png",
    homeimagemanage:imgroute + "homeimagemanage.png",
    tablemanage:imgroute + "tablemanage.png",
    closeshop:imgroute + "closeshop.png",
    printer:imgroute + "printer.png",
    business:imgroute + "business.png",
    trash:imgroute + "trash.png",
    open:imgroute + "open.png",
    close:imgroute + "close.png",
    imgNa:imgroute + "img-na.png",
    statute:imgroute + "statute.png",
    faq:imgroute + "faq.png",
    improve:imgroute + "improve.png",
    consult:imgroute + "consult.png",
    about:imgroute + "about.png",
    infoerro: imgroute + "info-erro.png",
    infoico: imgroute + "info-ico.png",
    inforight: imgroute + "info-right.png",
    customtypeadd: imgroute + "custom_type_add.png",
    defaulttypeadd: imgroute + "default_type_add.png",
    typedel: imgroute + "type_del.png",
    customfoodadd: imgroute + "custom_food_add.png",
    defaultfoodadd: imgroute + "default_food_add.png",
    lotdiscount: imgroute + "lot_discount.png",
    lotrecommend: imgroute + "lot_recommend.png",
    lotnorecommend: imgroute + "lot_norecommend.png",
    lotputon: imgroute + "lot_puton.png",
    lotputoff: imgroute + "lot_putoff.png",
    qrprinter: imgroute + "qr_print.png",
}

export default
{
    defaults,
    imgroute
}
